log_path: /home/yxt/code/slam/intensity_calib_fred_ws/src/intensity_calibration/log/
result_path: /home/yxt/code/slam/intensity_calib_fred_ws/src/intensity_calibration/results/
# poincloud
voxel_size: 0.4
max_distance: 30
# 
std_var: 1
eps: 0.1
